### ISSUE TITLE
Macro Bug regarding adding/sending multiple copies of the same card + Suggestions + Question

### ISSUE THREAD

**Issue by Frightfur** [killburne/custom-duelingbook#1]
Bug: When I attempted to resolve the effect of Thunder Dragon, the function ${addFromDeckToHand(Thunder Dragon~Thunder Dragon)} only adds 1 Thunder Dragon. I tested adding different cards with different names in that line of code and it worked fine so I think it has to do when 2 of the same card are listed. I tried something very similar for Toon Table of Contents (trying to send multiple copies of the same card with 1 function) and banishing the same names from GY but needed to separate all in separate functions for them to work.

Here are some suggestions for cards that could use functions if they are possible to do (I have no idea if they are possible)
Banishing from Deck for cards like Gold Sarc and Nobleman of Crossout
Returning backrow from field to hand like Giant Trunade and Hey Trunade
Some kind of mulligan command for Reload
Calculating the number of cards a player controls and/or in hand for cards like Secret Barrel and Just Desserts 

Question
Is there a better way to program Scapegoat. This is my configuration, I'm mostly wondering if I'm not missing something as simple as putting a number in the brackets because I tried putting 4 in there and it did not special summon 4 tokens. 
Scapegoat | ${specialSummonToken()} | ${waitInMs(0)} | ${specialSummonToken()} | ${waitInMs(1000)} | ${specialSummonToken()} | ${waitInMs(1000)} | ${specialSummonToken()}

**Comment by killburne** [comment]
Using the same card name multiple times in a command now works properly.

I also just added a couple new macro functions such as ``banishFromDeck`` and ``specialSummonMultipleTokens``.
Calculating card count and return cards from field to hand is something I might do later.
