### ISSUE TITLE
I can't copy paste in deck constructor

### ISSUE THREAD

**Issue by Frightfur** [killburne/custom-duelingbook#5]
If I ctrl + c card name or effect in deck constructor (this is Into the Void) I get this (I can only copy by clicking right click copy)

ydke://EtFCBRLRQgUS0UIFo6lXBaOpVwWjqVcFg+DBBIPgwQSD4MEEcsqPA10G5AD5vr0Anaq7ADUMrgHUFrYD1Ba2A9QWtgNvvjEEb74xBG++MQR/gZkFf4GZBX+BmQWEqkUChKpFAoSqRQKTy10Ck8tdApPLXQLlvacB5b2nAeW9pwFP6N4FT+jeBXRHKwE5QFgE1CccABSNnwQm6wAE7iX+BA==!RmAzAE6y6gVs2xABPMqVAYTZ/wK7kQgCgT9EAYE/RAFngA8EGaKKAbe/YgSAfJMEviOnAr4jpwItPVkC!!

**Comment by killburne** [comment]
ctrl + c exports your deck to ydke so you can paste it into omega and ctrl + v imports the ydke format, but i now made it that ctrl +c and ctrl + v dont get overriden while you focus an input so you can copy & paste text like normal
