### ISSUE TITLE
Doesn't seem to work at all today.

### ISSUE THREAD

**Issue by funkyluca** [killburne/custom-duelingbook#6]
Today script doesn't work, when i load duelingbook page all the images saved in the script are loaded and showed all at once in the first page. If i try to login and start/watch a game i face other problems so it's not possible to play at all today with the script on. I tried to update, resetted both settings on duelingbook and tampermonkey but didnt solved the issue. The only thing i noticed is there are some syntax mistakes in the code highlighted by tampermonkey when i checked, but i don't know if are correlated with this today malfunction.
I'm on google chrome and last night it worked fine.
![wooow](https://user-images.githubusercontent.com/124280831/216365586-1284408e-7002-4c05-b1ba-29011389b5eb.png)

**Comment by killburne** [comment]
DB made a change regarding pendulum artwork that made my changes break the site, but i fixed it now. if you update it should work again
